pkg: one script

diff --git a/pkg b/pkg
--- a/pkg
+++ b/pkg
@@ -37,8 +37,14 @@ pkg_verify() {
 }
 
 pkg_manifest() {
-    cd "$pkgfile_pwd/build/pkg"
-    find . -mindepth 1 | sed 's/^\.//' > ../../.manifest
+    cd "$og_pwd/build/pkg"
+
+    _() { find . -mindepth 1 -type "$1" | sed 's/^\.//'; }
+    _ f > ../../.manifest
+
+    printf '%s\n' "/var/db/pm/$name-manifest" >> ../../.manifest
+
+    _ d | sort -r >> ../../.manifest
 }
 
 pkg_extract() {
@@ -64,7 +70,7 @@ pkg_extract() {
 
 pkg_build() {
     cd src >/dev/null || die "can't access src dir."
-    BUILD=$pkgfile_pwd/build/pkg
+    BUILD=$og_pwd/build/pkg
 
     set -e
     build || die "failed to build $name-$version"
@@ -72,7 +78,7 @@ pkg_build() {
 
     pkg_manifest
 
-    cd "$pkgfile_pwd"
+    cd "$og_pwd"
 
     cp .manifest "build/pkg/var/db/pm/$name-manifest"
     tar cvf "$name-$version-$release.tar.gz" -C build/pkg . >/dev/null ||
@@ -80,6 +86,36 @@ pkg_build() {
 
     log "successfuly built $name"
     log "package is at $name-$version-$release.tar.gz"
+}
+
+pkg_add() {
+    [ -f "$1" ] || die "add needs a tarball"
+    [ -z "${1##*.tar.??}" ] || die "argument is not a tarball"
+
+    # Temporary.
+    mkdir -p "$ROOT"
+
+    tar xvf "$1" -C "$ROOT" || die "couldn't extract $1"
+}
+
+pkg_delete() {
+    pkg_db="$ROOT/var/db/pm/$1-manifest"
+
+    [ -z "$1" ] &&      die "delete needs an argument"
+    [ -f "$pkg_db" ] || die "package not installed"
+
+    while read -r line; do
+        # Temporary
+        line=$ROOT/$line
+
+        [ -f "$line" ] && rm "$line"
+
+        # Only delete empty directories.
+        [ -d "$line" ] && {
+            find "$line" -mindepth 1 | read -r ||
+                rmdir "$line"
+        }
+    done < "$pkg_db"
 }
 
 pkg_checksum() {
@@ -101,7 +137,7 @@ is_remote() {
 }
 
 clean() {
-    [ -d "$pkgfile_pwd/build" ] && rm -rf "$pkgfile_pwd/build"
+    [ -d "$og_pwd/build" ] && rm -rf "$og_pwd/build"
 }
 
 die() {
@@ -114,33 +150,47 @@ log() {
 }
 
 args() {
-    [ -z "$1" ] && return
+    case $1 in
+        a*)
+            pkg_add "$2"
+        ;;
 
-    [ "$1" = -v ] && printf '%s\n' "mkpkg 0.1.0"
-    [ "$1" = -h ] && printf '%s\n' "usage: mkpkg, mkpkg checksum " >&2
+        b*)
+            pkgfile_read
 
-    [ "$1" = checksum ] && {
-        pkg_get
-        pkg_checksum .checksum
-    }
-    exit
+            [ -f .checksum ] || die "checksums not found, run 'mkpkg checksum'"
+
+            pkg_get
+            pkg_verify
+            pkg_extract >/dev/null
+            pkg_build
+        ;;
+
+        c*)
+            pkgfile_read
+            pkg_get
+            pkg_checksum .checksum
+        ;;
+
+        d*) pkg_delete "$2" ;;
+        -v) printf '%s\n' "mkpkg 0.1.0" ;;
+
+        *)
+            printf '%s\n' "usage: pkg [[a]dd,[b]uild,[c]hecksum],[d]el,[l]ist]"
+        ;;
+    esac
 }
 
 main() {
-    pkgfile_pwd=$PWD
+    og_pwd=$PWD
+
+    # Temporary.
+    ROOT=~/.fakeroot
 
     trap clean EXIT INT
     clean
 
-    pkgfile_read
     args "$@"
-
-    [ -f .checksum ] || die "checksums not found, run 'mkpkg checksum'"
-
-    pkg_get
-    pkg_verify
-    pkg_extract >/dev/null
-    pkg_build
 }
 
 main "$@"
