pkg: store cached files by name

diff --git a/pkg b/pkg
--- a/pkg
+++ b/pkg
@@ -29,17 +29,17 @@ pkg_deps() {
 
 pkg_get() {
     mkdir -p build || die "couldn't create build dir"
-    mkdir -p "$PKG_ROOT/$tar_dir" || die "couldn't create cache dir"
+    mkdir -p "$PKG_ROOT/$tar_dir/$name" || die "couldn't create cache dir"
 
     for src in $source; do
         if is_remote "$src"; then
-            [ -f "$PKG_ROOT/$tar_dir/${src##*/}" ] && {
+            [ -f "$PKG_ROOT/$tar_dir/$name/${src##*/}" ] && {
                 log "found cached $src"
                 continue
             }
 
             log "downloading $src"
-            wget -P "$PKG_ROOT/$tar_dir" -- "$src" ||
+            wget -P "$PKG_ROOT/$tar_dir/$name" -- "$src" ||
                 die "failed to download $src"
         else
             [ -f "$src" ] && continue
@@ -73,18 +73,18 @@ pkg_extract() {
     mkdir -p src "pkg/$db_dir/$name"
 
     for pkg in $source; do
-        pkg_name=${pkg##*/}
+        file_name=${pkg##*/}
 
         case $pkg in
             *.tar|*.tar.gz|*.tar.xz|*.tar.bz2|*.tar.lzma|\
             *.tar.lz|*.txz|*.tgz|*.tbz2|*.zip|*.rpm|*.7z)
-                tar xavf "$PKG_ROOT/$tar_dir/$pkg_name" \
+                tar xavf "$PKG_ROOT/$tar_dir/$name/$file_name" \
                     -C src \
                     --strip-components 1 \
-                || die "couldn't extract $pkg_name"
+                || die "couldn't extract $file_name"
             ;;
 
-            *)  cp -f "../$pkg_name" src ;;
+            *)  cp -f "../$file_name" src ;;
         esac
     done
 
@@ -157,7 +157,7 @@ pkg_list() {
 pkg_checksum() {
     for src in $source; do
         if is_remote "$src"; then
-            files="$files $PKG_ROOT/$tar_dir/${src##*/}"
+            files="$files $PKG_ROOT/$tar_dir/$name/${src##*/}"
         else
             files="$files $src"
         fi
