Sign all packages. (#2)
* pkgs: initial signify support

diff --git a/pkg b/pkg
--- a/pkg
+++ b/pkg
@@ -23,20 +23,15 @@ pkgfile_read() {
 }
 
 pkg_get() {
-    tar_cache=$PKG_ROOT/$tar_dir/$name
-    mkdir -p build "$tar_cache" || die "couldn't create dirs"
+    mkdir -p build || die "couldn't create build dir"
 
     for src in $source; do
-        if is_remote "$src"; then
-            [ -f "$tar_cache/${src##*/}" ] && {
-                log "found cached $src"
-                continue
-            }
+        [ -f "${src##*/}" ] && continue
 
+        if is_remote "$src"; then
             log "downloading $src"
-            wget -P "$tar_cache" -- "$src" || die "failed to download $src"
+            wget -- "$src" || die "failed to download $src"
         else
-            [ -f "$src" ] && continue
             die "source file $src not found"
         fi
     done
@@ -48,6 +43,24 @@ pkg_verify() {
     diff .checksum build/.checksum ||
         die "checksum of sources does not match checksum of package" \
             "run 'pkg checksum' to update checksums"
+
+    type signify >/dev/null || {
+        log "WARNING: signify not found"
+        log "WARNING: signature checking disabled"
+        return
+    }
+
+    [ -f .signature ] && {
+        printf '%s\n%s\n' \
+               "untrusted comment: KISS public key" \
+               "RWRQRltQ0dAMYCAYfTCRyq1eb+da5qGa7HTL8cml9qLOcbfuuvFQcX+7" \
+        > kiss-signature
+
+        signify -C  -p kiss-signature -x .signature ||
+            die "failed to verify signature"
+
+        log "verified signatures"
+    }
 }
 
 pkg_manifest() {
@@ -72,14 +85,13 @@ pkg_extract() {
 
         case $pkg in
             *.tar|*.tar.??|*.tar.???|*.tar.????)
-                tar xf "$PKG_ROOT/$tar_dir/$name/$file_name" \
-                    -C src --strip-components 1 ||
+                tar xf "../$file_name" -C src --strip-components 1 ||
                     die "couldn't extract $file_name"
             ;;
 
             *.zip)
                 log "warn: You may need to cd into zip directory."
-                unzip -qd src "$PKG_ROOT/$tar_dir/$name/$file_name" ||
+                unzip -qd src "../$file_name" ||
                     die "couldn't extract $file_name"
             ;;
 
@@ -102,15 +114,16 @@ pkg_build() {
     cd "$og_pwd" >/dev/null
 
     cp .manifest "build/pkg/$db_dir/$name/manifest"
-    tar pcvf "${name}_$version-$release.tar.gz" \
+    tar pcvf "PKG-${name}_$version-$release.tar.gz" \
         -C build/pkg . >/dev/null || die "failed to create package"
 
     log "successfuly built $name"
-    log "package is at ${name}_$version-$release.tar.gz"
+    log "package is at PKG-${name}_$version-$release.tar.gz"
 }
 
 pkg_add() {
     name=${1%_*.tar.gz*}
+    name=${name##PKG-}
 
     [ -f "$1" ] || die "file not found"
     [ -z "${1##*.tar.??}" ] || die "add requires a tarball"
@@ -165,14 +178,15 @@ pkg_list() {
 pkg_checksum() {
     for src in $source; do
         if is_remote "$src"; then
-            files="$files $PKG_ROOT/$tar_dir/$name/${src##*/}"
+            files="$files ${src##*/}"
         else
             files="$files $src"
         fi
     done
 
-    sha256sum -- $files | sed "s|${PKG_ROOT:-///}||" > "$1" ||
-        die "failed to generate checksums"
+    sha256sum -- pkgfile $files \
+        | awk '{print "SHA256 ("$2") = "$1}' > "$1" ||
+          die "failed to generate checksums"
     log "Saved checksum to $1"
 }
 
@@ -184,6 +198,7 @@ clean() {
     [ "$pkgfile" = 1 ] || return
     [ -f "$og_pwd/pkgfile" ] || return
     rm -rf "$og_pwd/build"
+    rm kiss-signature 2>/dev/null
 }
 
 die() {
@@ -237,7 +252,6 @@ main() {
 
     og_pwd=$PWD
     db_dir=var/db/pkg
-    tar_dir=var/cache/pkg
 
     trap clean EXIT
     clean
