pkgs: swap to vanilla sha256sum output

diff --git a/pkg b/pkg
--- a/pkg
+++ b/pkg
@@ -166,9 +166,7 @@ pkg_checksum() {
         fi
     done
 
-    sha256sum -- $files | awk '{print "SHA256 ("$2") = "$1}' > "$1" ||
-          die "failed to generate checksums"
-
+    sha256sum -- $files > "$1" || die "failed to generate checksums"
     log "Saved checksum to $1"
 }
 
